imports:
    - { resource: alias.yml }

services:
    _defaults:
        autowire: true
        bind:
            $tables: '%tables%'		
            $ext_images_path: '%core.root_path%ext/david63/autodbbackup/adm/style/images'
        public: true

    david63.statsonindex.listener:
        class: david63\statsonindex\event\listener
        tags:
            - { name: event.listener }

    david63.statsonindex.admin.controller:
        class: david63\statsonindex\controller\admin_controller

    david63.statsonindex.main.controller:
        class: david63\statsonindex\controller\main_controller

    david63.statsonindex.core.functions:
        class: david63\statsonindex\core\functions
